# Site settings
#gh-pages
title: WSHS AMPLIFIED
header-img: img/home-bg.jpg
email: woodbridgeamplified@gmail.com
copyright_name: Amplified Inc.
description: "A digital platform that empowers students by amplifying their voices to higher levels of administration."
baseurl: "/school-amp-1"
url: "http://yourdomain.com"
twitter_username: WSHSAmplified
github_username:  WSHSAmplified
facebook_username:  WSHSAmplified
email_username:  your-email@yourdomain.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
