# Site settings
#gh-pages
title: WSHS AMPLIFIED
header-img: img/home-bg.jpg
email: woodbridgeamplified@gmail.com
copyright_name: Amplified Inc.
description: "A digital platform that allows student, teachers, and administration to find solutions to problems in their learning environments."
baseurl: ""
url: https://www.wshsamplified.com   # with the https protocol
enforce_ssl: wshsamplified.com   # without any protocol
twitter_username: WSHSAmplified
github_username:  jose-reyes-9
facebook_username:  wshs amplified
email_username:  woodbridgeamplified@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
